# Generated by Django 4.0.3 on 2022-03-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
