# Generated by Django 4.0.3 on 2022-03-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customuser_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='file',
        ),
    ]
